import { AddTodo } from '@/components/AddTodo';
import { Header } from '@/components/Header';
import { TodoList } from '@/components/TodoList';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <main style={{ width: '-webkit-fill-available' }}>
      <div className='container mx-auto max-w-md'>
        <Header />
        <AddTodo />
        <TodoList />
      </div>
    </main>
  );
}

